# Generated by Django 4.0.5 on 2022-07-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age_inYears', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
